# Site
title: 'seaweed.dk'
description: 'Personal Hub'
keywords: 'christian tang, tang, tangc, christensen, cv, curriculum vitae, curriculum-vitae, google, google+, linkedin, twitter, instagram, github, weblog, blog'
url: 'http://seaweed.dk'
repository: TangChr/TangChr.github.io

# Author
author:
  name: 'Christian Tang Christensen'

# Paths
layouts_dir: 'src/layouts'
includes_dir: 'src/includes'
data_dir: 'data'
sass:
    load_paths:
        - 'src/css'
        - 'res/sticky-notes'

# Build
environment: production
baseurl: '/'

exclude:
  - res
  - vendor
  - src
  - data
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - serve.ps1