# Site
title: "seaweed.dk"
description: "Social Hub"
keywords: "christian tang, tang, tangc, christensen, cv, curriculum vitae, curriculum-vitae, google, google+, linkedin, twitter, instagram, github, weblog, blog"

url: http://seaweed.dk
baseurl: '/'

# Author
author:
  name: "Christian Tang Christensen"

# Build
environment: production

# Excludes
exclude: [CNAME, Gemfile, Gemfile.lock, serve.cmd, LICENSE, README.md]