# Site
title: 'seaweed.dk'
description: 'Personal Hub'
keywords: 'christian tang, tang, tangc, christensen, cv, curriculum vitae, curriculum-vitae, google, google+, linkedin, twitter, instagram, github, weblog, blog'
url: 'http://seaweed.dk'
repository: TangChr/TangChr.github.io

# Author
author:
  name: 'Christian Tang Christensen'

# Build
environment: production
baseurl: '/'
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - serve.cmd
  - vendor
  
sass:
    load_paths:
        - "_sass/sticky-notes"