# Site Information
title: "seaweed.dk"
url: http://seaweed.dk
keywords: "christian tang, tang, tangc, christensen, cv, curriculum vitae, curriculum-vitae, google, google+, linkedin, twitter, instagram, github, weblog, blog"

# Author
author:
  name: "Christian Tang Christensen"
  uri: http://seaweed.dk

# Build settings
baseurl: /
destination: _site
kramdown:
  input: GFM
  
# Excludes
exclude: [CNAME, Gemfile, Gemfile.lock, serve.cmd, LICENSE, README.md]