# Site Information
title: "seaweed.dk"
url: http://seaweed.dk
author: "Christian Tang Christensen"
keywords: "christian tang, tang, tangc, christensen, cv, curriculum vitae, curriculum-vitae, google, google+, linkedin, twitter, instagram, github, weblog, blog"

# Settings
baseurl: /
markdown: redcarpet
sass:
    style: expanded