# Site
title: 'seaweed.dk'
description: 'Personal Hub'
keywords: 'christian tang, tang, tangc, christensen, cv, curriculum vitae, curriculum-vitae, google, google+, linkedin, twitter, instagram, github, weblog, blog'
url: 'http://seaweed.dk'

# Repository
repo:
  name:      'TangChr.github.io'
  github_url: 'https://github.com/TangChr/TangChr.github.io'
  travis_url: 'https://travis-ci.org/TangChr/TangChr.github.io'
  travis_svg: 'https://travis-ci.org/TangChr/TangChr.github.io.svg?branch=master'

# Author
author:
  name: 'Christian Tang Christensen'
  twitter: TangChr

# Build
environment: production
baseurl: '/'
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - serve.cmd
  - vendor